Update Docs: Configuration “configuration-options”
decaporg/decap-cms pull request #6628
Opened 2022-12-18 19:15 UTC by Zearin

Automatically generated by Netlify CMS

2022-12-18 19:21 UTC, Zearin commented
(Wow, it really created a PR automatically based on my edits!  That is very cool.)

Just learning about this project, and thought I’d try and contribute a few small edits to the docs.

According to the docs style guide, documentation shouldn’t include latin abbreviations (like “e.g.” or “i.e.”), with the sole exception of “etc.”.  

Most of this PR is correcting this discrepancy, with a few other small copy-edits as well.

2023-04-25 12:56 UTC, martinjagodic requested changes

2023-04-25 12:56 UTC, martinjagodic commented on website/content/docs/configuration-options.md
> -For folder collections where users can create new items, the `slug` option specifies a template for generating new filenames based on a file's creation date and `title` field. (This means that all co
Please keep the link

2024-02-03 12:25 UTC, privatemaker commented
@Zearin I can also take this one too, if you'd like!!

2024-02-03 18:35 UTC, martinjagodic commented
@Zearin @privatemaker I created the new repo at https://github.com/decaporg/decap-website, so this PR would have to be created again on that repo. Sorry for the mess, I kinda missed it.

2024-06-27 05:22 UTC, closed without merging