style: align SidebarHeading with TopHeading
decaporg/decap-cms pull request #6988
Opened 2023-11-23 10:39 UTC by olegfedak

**Summary**
It's just a small fix of styles without changing the design.

**As a result**
<img width="414" alt="decap-style-fix" src="https://github.com/decaporg/decap-cms/assets/5526547/a3d4717f-8069-4f1c-944b-dfd245a6b4aa">

2023-11-23 12:05 UTC, martinjagodic approved these changes

2023-11-24 08:42 UTC, martinjagodic approved these changes

2023-11-28 22:54 UTC, olegfedak reviewed
**Summary**
It's just a small fix of styles without changing the design.

**As a result**
<img width="602" alt="Знімок екрана 2023-11-24 о 14 55 14" src="https://github.com/decaporg/decap-cms/assets/5526547/5815c554-2aca-4451-8740-43ce02f4e6a3">

2023-11-29 08:29 UTC, martinjagodic approved these changes
@olegfedak this looks nice, thanks! If you indend to add more changes to this PR please convert it to draft. It doesn't make much sense to review every commit :)

2023-11-29 16:20 UTC, olegfedak commented
> @olegfedak this looks nice, thanks! If you indend to add more changes to this PR please convert it to draft. It doesn't make much sense to review every commit :)

Oh, I will! It seems I didn't completely understand how the pull request works. I might should work in a branch from the forked repo master

2023-11-30 08:07 UTC, martinjagodic commented
That's ok. Mark it as ready for review when you're done.

2023-12-01 23:31 UTC, olegfedak reviewed
**Result:**
<img width="284" alt="Знімок екрана 2023-12-02 о 00 34 06" src="https://github.com/decaporg/decap-cms/assets/5526547/a6a80641-0ed9-4d91-a76d-df25d9489de4">

2023-12-07 08:21 UTC, martinjagodic approved these changes

2024-01-08 14:07 UTC, martinjagodic requested changes

2024-01-08 14:07 UTC, martinjagodic commented on dev-test/config.yml
Removing restaurants and color is not in the scope of this PR. Please add it back.

2024-02-01 12:49 UTC, martinjagodic approved these changes

2024-02-01 13:25 UTC, merged