Update Docs: migrate Beta Features - Editorial Workflow
decaporg/decap-cms pull request #7044
Opened 2024-01-19 12:07 UTC by privatemaker

Continuing migration of Beta Features Documentation #7040

@martinjagodic slightly cleaner this time- last one was made editing within Decap and merging 🥲

2024-01-19 12:16 UTC, privatemaker commented
Or perhaps this should go in the `Workflow` group?

2024-01-19 12:18 UTC, martinjagodic commented
I vote for the workflow group.

2024-01-19 12:47 UTC, privatemaker commented
Ok. This is now in Workflow Group. I reworked the text a little bit.

2024-01-19 13:20 UTC, martinjagodic requested changes
see above

2024-01-19 13:27 UTC, privatemaker commented
I removed the whitespace!

2024-01-19 15:40 UTC, privatemaker commented
While combing through the docs, I noticed this feature is also mentioned in two other places which cross link to one-another and repeat information which is also (now) getting it's own page with this pull-req.

- [Configuration Options > Publish Mode
](https://decapcms.org/docs/configuration-options/#publish-mode)
- [Add to your Site > Editorial Workflow](https://decapcms.org/docs/add-to-your-site/#editorial-workflow)

I think this should be simplified with both of those sections mentioning and linking to the newly created page.

2024-01-22 08:25 UTC, martinjagodic commented
I agree, can you do that as part of this PR?

2024-01-22 23:59 UTC, privatemaker commented
Yep. I've done what I think makes most sense in terms of consolidating and trimming. By my eye this is ready for merging.

2024-01-23 08:41 UTC, martinjagodic requested changes
All good except that link.

2024-01-23 08:41 UTC, martinjagodic commented on website/content/docs/editorial-workflows.md
> +**Note:** Editorial workflow works with GitHub repositories, and support for GitLab and Bitbucket is [in beta](/docs/beta-features/#gitlab-and-bitbucket-editorial-workflow-support).
This link will not work anymore. We could link to open issues with the EF tag. This way we might get some contributions. 

link: https://github.com/decaporg/decap-cms/issues?q=is%3Aissue+is%3Aopen+label%3A%22area%3A+ui%2Feditorial-workflow%22

2024-01-23 09:17 UTC, martinjagodic approved these changes

2024-01-23 09:17 UTC, merged