Update Docs: migrate Beta Features - GraphQL APIs
decaporg/decap-cms pull request #7046
Opened 2024-01-19 12:25 UTC by privatemaker

Continuing migration of Beta Features Documentation #7040

@martinjagodic i'll stop here until I get a confirmation my workflow here works for you 😉

2024-01-19 13:22 UTC, martinjagodic requested changes

2024-01-19 13:22 UTC, martinjagodic commented on website/content/docs/github-backend.md
> +Experimental support for GitHub's [GraphQL API](https://developer.github.com/v4/) is now available for the GitHub backend.
Let's remove this line as it's not flagged as experimental anymore.

2024-01-19 13:22 UTC, martinjagodic commented on website/content/docs/gitlab-backend.md
> +Experimental support for GitLab's [GraphQL API](https://docs.gitlab.com/ee/api/graphql/) is now available for the GitLab backend.
Let's remove this line as it's not flagged as experimental anymore.

2024-01-19 14:17 UTC, privatemaker commented
Pushed your request and moved the **Note: ...** bit to bottom.

2024-01-22 08:37 UTC, martinjagodic reviewed
@privatemaker I would keep the note under title. It could be frustrating for someone to go over the tutorial and only then realising it's not compatible with their setup. What do you think?

2024-01-22 10:08 UTC, privatemaker commented
Hrm, if a user is interested in using `github` or `gitlab` backend, I assume user knows they are not using `git-gateway` as a backend. So why the need for the **Note: ...** at all?

But not that big of a deal. I moved it back under the header.

2024-01-22 10:19 UTC, martinjagodic approved these changes

2024-01-22 10:21 UTC, merged