Update Docs: migrate Beta Features - Summary String Transformations
decaporg/decap-cms pull request #7061
Opened 2024-01-23 10:13 UTC by privatemaker

Relating to #7040

2024-01-23 11:48 UTC, martinjagodic requested changes

2024-01-23 11:48 UTC, martinjagodic commented on website/content/docs/summary-strings.md
> +title: File Collections
I believe this one should be `group`

2024-01-23 12:50 UTC, privatemaker commented on website/content/docs/summary-strings.md
> +title: File Collections
🤦🏻‍♀️ Doh! Fixed.

2024-01-29 10:54 UTC, martinjagodic approved these changes

2024-01-29 10:54 UTC, merged