fix: clear field error in Editor after the field value is changed
decaporg/decap-cms pull request #7216
Opened 2024-05-28 04:01 UTC by olegfedak

### **Summary**
There is a situation when several fields are highlighted as "required" at the same time. It looks like red frames inside of red frames when it comes to nested widgets. When you make changes to these fields, the errors do not disappear. It's confusing because it's not clear how many fields are left, especially when the page needs to be scrolled.

I expect that when the user changes the value of the field, the error disappears, no need to "signal" with red.

### Changes that allow to achieve that
1. **Modified the` clearFieldErrors` action:**
Created an action `clearFieldErrors` in the `entries.js` file that accepts `uniqueFieldId` as a parameter and returns an action object with type `DRAFT_CLEAR_ERRORS` and the passed `uniqueFieldId`.

2. **Added `DRAFT_CLEAR_ERRORS` handling in the reducer:**
In the `entryDraftReducer`, added handling for the `DRAFT_CLEAR_ERRORS` action, which removes errors for a specific field using `uniqueFieldId`.

3. **Updated the `EditorControl` component:**
In the `EditorControl` component, invoked `clearFieldErrors` when the field value changes, passing `uniqueFieldId` as an argument. This was done through props, using the `mapDispatchToProps` function that wraps `clearFieldErrors` in `dispatch`.

4. **Ensured proper action `dispatch` in onChange:**
Added a call to `clearFieldErrors` in the `onChange` function to clear errors only for the specific field, using the passed `uniqueFieldId`.

By doing this, we ensured that errors are cleared only for the specific field when its value changes.

### How it looks

https://github.com/decaporg/decap-cms/assets/5526547/656b82c3-c80b-427f-903e-1b36b1e44dc7

2024-05-28 19:50 UTC, olegfedak commented
I noticed the fields were jumping when there is a field error. Just added a common `flex div` for the label and error line to correct the display.


https://github.com/decaporg/decap-cms/assets/5526547/45e47a4a-2cd4-4972-9deb-10026088e769

2024-08-01 13:35 UTC, martinjagodic commented
@olegfedak is this PR still a work in progress?

2024-08-02 01:10 UTC, olegfedak commented
> @olegfedak is this PR still a work in progress?

Well, it's ready but strugled on the tests

2024-08-21 09:15 UTC, martinjagodic requested changes

2024-08-22 00:37 UTC, olegfedak commented on cypress/utils/steps.js
> +    .first() // Вибрати перший елемент після parents()
Fixed

2024-08-22 07:27 UTC, martinjagodic approved these changes

2024-11-12 14:44 UTC, merged

2025-01-13 14:17 UTC, Scutua approved these changes